import AppLayout from '@/components/Layout/AppLayout'
import Head from 'next/head'
import { Loading } from '../components/screens/Loading';
import HomePage from '../components/screens/HomePage';
import AboutPage from '../components/screens/AboutPage';
import Projects from '../components/screens/Projects';
import ContactPage from '../components/screens/ContactPage';
import Footer from '../components/organisms/Footer/Footer';
import {Element }from 'react-scroll';

export default function Home() {
  return (
    <>
      <Head>
        <title>Gustavo Riera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo-JM.png" />
      </Head>
      <Loading/>
      <AppLayout>
        <Element name='Home'>
          <HomePage/>
        </Element>
        <Element name='About'>
          <AboutPage/>
        </Element>
        <Element name='Projects'>
          <Projects/>
        </Element>
        <Element name='Contact'>
          <ContactPage/>
        </Element>
        <Footer/>
      </AppLayout>
    </>
  )
}
